In [1]:
import pandas as pd

In [2]:
accidents_df = pd.read_csv("accident.csv",low_memory=False)

In [3]:
accidents_df.head()

,STATE,ST_CASE,VE_TOTAL,VE_FORMS,PVH_INVL,PEDS,PERNOTMVIT,PERMVIT,PERSONS,COUNTY,...,NOT_MIN,ARR_HOUR,ARR_MIN,HOSP_HR,HOSP_MN,CF1,CF2,CF3,FATALS,DRUNK_DR
0,1,10001,1,1,0,0,0,1,1,73,...,31,9,36,88,88,0,0,0,1,1
1,1,10002,1,1,0,0,0,2,2,73,...,99,20,5,99,99,0,0,0,1,1
2,1,10003,2,1,1,0,1,1,2,73,...,99,2,31,88,88,0,0,0,1,0
3,1,10004,1,1,0,0,0,1,1,73,...,99,21,57,99,99,0,0,0,1,1
4,1,10005,1,1,0,0,0,1,1,73,...,7,20,10,88,88,0,0,0,1,0

In [4]:
states = {1: 'Alabama', 2: 'Alaska', 4: 'Arizona', 5: 'Arkansas', 
          6: 'California', 8: 'Colorado', 9: 'Connecticut', 10: 'Delaware', 
          11: 'District of Columbia', 12: 'Florida', 13: 'Georgia', 15: 'Hawaii', 
          16: 'Idaho', 17: 'Illinois', 18: 'Indiana', 19: 'Iowa', 20: 'Kansas', 
          21: 'Kentucky', 22: 'Louisiana', 23: 'Maine', 24: 'Maryland', 
          25: 'Massachusetts', 26: 'Michigan', 27: 'Minnesota', 
          28: 'Mississippi', 29: 'Missouri', 30: 'Montana', 31: 'Nebraska', 
          32: 'Nevada', 33: 'New Hampshire', 34: 'New Jersey', 35: 'New Mexico', 
          36: 'New York', 37: 'North Carolina', 38: 'North Dakota', 39: 'Ohio', 
          40: 'Oklahoma', 41: 'Oregon', 42: 'Pennsylvania', 43: 'Puerto Rico', 
          44: 'Rhode Island', 45: 'South Carolina', 46: 'South Dakota', 47: 'Tennessee', 
          48: 'Texas', 49: 'Utah', 50: 'Vermont', 51: 'Virginia', 52: 'Virgin Islands', 
          53: 'Washington', 54: 'West Virginia', 55: 'Wisconsin', 56: 'Wyoming'}

accidents_df['State']=accidents_df['STATE'].apply(lambda x:states[x])

In [5]:
accidents_df

,STATE,ST_CASE,VE_TOTAL,VE_FORMS,PVH_INVL,PEDS,PERNOTMVIT,PERMVIT,PERSONS,COUNTY,...,ARR_HOUR,ARR_MIN,HOSP_HR,HOSP_MN,CF1,CF2,CF3,FATALS,DRUNK_DR,State
0,1,10001,1,1,0,0,0,1,1,73,...,9,36,88,88,0,0,0,1,1,Alabama
1,1,10002,1,1,0,0,0,2,2,73,...,20,5,99,99,0,0,0,1,1,Alabama
2,1,10003,2,1,1,0,1,1,2,73,...,2,31,88,88,0,0,0,1,0,Alabama
3,1,10004,1,1,0,0,0,1,1,73,...,21,57,99,99,0,0,0,1,1,Alabama
4,1,10005,1,1,0,0,0,1,1,73,...,20,10,88,88,0,0,0,1,0,Alabama
5,1,10006,1,1,0,0,0,1,1,109,...,1,31,88,88,0,0,0,1,0,Alabama
6,1,10007,1,1,0,0,0,1,1,117,...,23,39,88,88,0,0,0,1,0,Alabama
7,1,10008,1,1,0,0,0,1,1,83,...,17,50,88,88,0,0,0,1,1,Alabama
8,1,10009,2,2,0,0,0,4,4,103,...,5,50,99,99,0,0,0,2,0,Alabama
9,1,10010,1,1,0,0,0,2,2,69,...,15,30,88,88,0,0,0,2,1,Alabama
10,1,10011,2,2,0,0,0,2,2,73,...,8,12,88,88,0,0,0,1,0,Alabama
11,1,10012,1,1,0,0,0,2,2,93,...,14,26,99,99,0,0,0,1,0,Alabama
12,1,10013,1,1,0,2,2,1,1,55,...,17,26,18,4,15,0,0,1,0,Alabama
13,1,10014,2,2,0,0,0,5,5,97,...,0,41,99,99,0,0,0,1,1,Alabama
14,1,10015,2,2,0,0,0,3,3,121,...,7,36,99,99,0,0,0,1,1,Alabama
15,1,10016,1,1,0,0,0,1,1,121,...,88,88,88,88,0,0,0,1,0,Alabama
16,1,10017,1,1,0,0,0,1,1,49,...,19,54,88,88,0,0,0,1,1,Alabama
17,1,10018,1,1,0,0,0,1,1,71,...,8,15,88,88,0,0,0,1,0,Alabama
18,1,10019,1,1,0,0,0,7,7,103,...,16,46,17,9,0,0,0,1,0,Alabama
19,1,10020,3,2,1,0,0,8,8,123,...,1,43,2,12,0,0,0,4,1,Alabama
20,1,10021,2,2,0,0,0,3,3,79,...,7,44,8,0,0,0,0,1,0,Alabama
21,1,10022,4,2,2,0,0,2,2,73,...,10,46,11,5,20,14,0,1,0,Alabama
22,1,10023,1,1,0,0,0,2,2,83,...,4,55,88,88,0,0,0,2,0,Alabama
23,1,10024,2,1,1,1,1,3,3,47,...,13,59,99,99,14,0,0,1,0,Alabama
24,1,10025,2,2,0,0,0,4,4,15,...,22,2,99,99,0,0,0,1,1,Alabama
25,1,10026,3,3,0,0,0,5,5,89,...,12,57,99,99,0,0,0,1,0,Alabama
26,1,10027,1,1,0,0,0,1,1,97,...,20,20,88,88,0,0,0,1,1,Alabama
27,1,10028,1,1,0,0,0,2,2,55,...,14,47,99,99,0,0,0,2,0,Alabama
28,1,10029,2,2,0,0,0,2,2,123,...,12,41,99,99,0,0,0,1,0,Alabama
29,1,10030,1,1,0,0,0,3,3,33,...,4,28,99,99,0,0,0,1,0,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34409,56,560071,2,2,0,0,0,3,3,29,...,12,28,99,99,0,0,0,2,0,Wyoming
34410,56,560072,1,1,0,0,0,1,1,33,...,7,0,88,88,0,0,0,1,1,Wyoming
34411,56,560073,2,2,0,0,0,4,4,31,...,21,44,88,88,0,0,0,1,0,Wyoming
34412,56,560074,1,1,0,0,0,2,2,31,...,16,57,17,52,0,0,0,1,0,Wyoming
34413,56,560075,1,1,0,0,0,3,3,27,...,12,35,12,50,0,0,0,1,0,Wyoming
34414,56,560076,1,1,0,1,1,1,1,21,...,20,53,21,20,0,0,0,1,0,Wyoming
34415,56,560077,1,1,0,0,0,1,1,7,...,17,35,88,88,0,0,0,1,1,Wyoming
34416,56,560078,2,2,0,0,0,3,3,1,...,14,7,88,88,0,0,0,1,0,Wyoming
34417,56,560079,2,2,0,0,0,2,2,33,...,21,45,21,52,0,0,0,1,1,Wyoming
34418,56,560080,1,1,0,0,0,1,1,37,...,4,43,5,43,0,0,0,1,1,Wyoming
34419,56,560081,2,2,0,0,0,3,3,9,...,9,51,10,41,0,0,0,1,0,Wyoming
34420,56,560082,1,1,0,0,0,1,1,21,...,15,23,88,88,0,0,0,1,0,Wyoming
34421,56,560083,3,3,0,0,0,3,3,37,...,9,42,10,19,0,0,0,1,0,Wyoming
34422,56,560084,1,1,0,0,0,1,1,1,...,5,26,88,88,0,0,0,1,1,Wyoming
34423,56,560085,1,1,0,0,0,1,1,25,...,16,22,88,88,0,0,0,1,1,Wyoming
34424,56,560086,1,1,0,0,0,1,1,23,...,2,46,88,88,0,0,0,1,1,Wyoming
34425,56,560087,1,1,0,0,0,1,1,19,...,17,10,18,24,0,0,0,1,1,Wyoming
34426,56,560088,1,1,0,0,0,1,1,13,...,14,57,15,45,0,0,0,1,1,Wyoming
34427,56,560089,2,2,0,0,0,2,2,13,...,17,12,17,50,0,0,0,1,1,Wyoming
34428,56,560090,1,1,0,1,1,1,1,13,...,6,35,7,1,0,0,0,1,0,Wyoming
34429,56,560091,1,1,0,0,0,1,1,19,...,9,31,88,88,0,0,0,1,1,Wyoming
34430,56,560092,2,2,0,0,0,5,5,1,...,23,21,0,32,0,0,0,2,0,Wyoming
34431,56,560093,1,1,0,0,0,2,2,19,...,18,43,19,26,0,0,0,1,0,Wyoming
34432,56,560094,2,2,0,0,0,5,5,21,...,18,29,18,46,0,0,0,1,0,Wyoming
34433,56,560095,2,2,0,0,0,7,7,13,...,0,36,1,2,0,0,0,3,0,Wyoming
34434,56,560096,2,2,0,0,0,5,5,7,...,16,47,18,21,19,0,0,1,0,Wyoming
34435,56,560097,2,2,0,0,0,4,4,27,...,9,26,9,49,0,0,0,1,0,Wyoming
34436,56,560098,2,1,1,1,1,1,1,19,...,99,97,99,97,0,0,0,1,0,Wyoming
34437,56,560099,1,1,0,0,0,1,1,7,...,4,49,88,88,0,0,0,1,0,Wyoming
34438,56,560100,2,2,0,0,0,4,4,21,...,13,51,15,4,0,0,0,1,0,Wyoming

In [6]:
accidents_df['State'].value_counts().to_frame()

                      State
Texas                  3407
California             3357
Florida                2933
Georgia                1422
North Carolina         1348
Pennsylvania           1088
Ohio                   1053
Illinois               1003
Michigan                980
Tennessee               966
New York                965
Alabama                 937
South Carolina          936
Missouri                868
Arizona                 865
Indiana                 768
Kentucky                763
Virginia                722
Louisiana               704
Mississippi             628
Oklahoma                624
New Jersey              569
Colorado                558
Wisconsin               544
Washington              504
Arkansas                488
Maryland                472
Oregon                  446
Kansas                  381
Massachusetts           359
New Mexico              358
Minnesota               357
Iowa                    356
Nevada                  303
Connecticut             281
Utah                    259
West Virginia           250
Idaho                   232
Nebraska                194
Montana                 171
Maine                   151
New Hampshire           130
Delaware                116
Hawaii                  109
South Dakota            103
North Dakota            102
Wyoming                 100
Alaska                   78
Vermont                  57
Rhode Island             48
District of Columbia     26

In [7]:
distract = {0: 'Not Distracted', 1: 'Looked But Did Not See',
           3: 'By Other Occupant(s)', 4: 'By a Moving Object in Vehicle',
           5: 'While Talking or Listening to Cellular Phone',
           6: 'While Manipulating Cellular Phone',
           7: 'While Adjusting Audio or Climate Controls',
           9: 'While Using Other Component/Controls Integral to Vehicle',
           10: 'While Using or Reaching For Device/Object Brought Into Vehicle',
           12: 'Distracted by Outside Person, Object or Event',
           13: 'Eating or Drinking',
           14: 'Smoking Related',
           15: 'Other Cellular Phone Related',
           16: 'No Driver Present/Unknown if Driver Present',
           17: 'Distraction/Inattention',
           18: 'Distraction/Careless',
           19: 'Careless/Inattentive',
           92: 'Distraction (Distracted), Details Unknown',
           93: 'Inattention (Inattentive), Details Unknown',
           96: 'Not Reported',
           97: 'Lost In Thought/Day Dreaming',
           98: 'Other Distraction',
           99: 'Unknown if Distracted'}

accidents_df['mdrdstrd'] = accidents_df['MDRDSTRD'].apply(lambda x:distract[x])

KeyError: 'MDRDSTRD'

In [9]:
accidents_df.columns

Index(['STATE', 'ST_CASE', 'VE_TOTAL', 'VE_FORMS', 'PVH_INVL', 'PEDS',
       'PERNOTMVIT', 'PERMVIT', 'PERSONS', 'COUNTY', 'CITY', 'DAY', 'MONTH',
       'YEAR', 'DAY_WEEK', 'HOUR', 'MINUTE', 'NHS', 'RUR_URB', 'FUNC_SYS',
       'RD_OWNER', 'ROUTE', 'TWAY_ID', 'TWAY_ID2', 'MILEPT', 'LATITUDE',
       'LONGITUD', 'SP_JUR', 'HARM_EV', 'MAN_COLL', 'RELJCT1', 'RELJCT2',
       'TYP_INT', 'WRK_ZONE', 'REL_ROAD', 'LGT_COND', 'WEATHER1', 'WEATHER2',
       'WEATHER', 'SCH_BUS', 'RAIL', 'NOT_HOUR', 'NOT_MIN', 'ARR_HOUR',
       'ARR_MIN', 'HOSP_HR', 'HOSP_MN', 'CF1', 'CF2', 'CF3', 'FATALS',
       'DRUNK_DR', 'State'],
      dtype='object')